# IBM Guestbook image version ibmcom/guestbook:v1
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2
name: vinicius

image:
  repository: ibmcom/guestbook
  tag: v1
  pullPolicy: Always

# For some dev env (like minikube), you may need to set the type to NodePort
service:
  name: vinicius-servicebook
  type: LoadBalancer
  port: 4000
  targetPort: 4000
